export const formDefaultData = (category = '') => {
  return {
    ingredients: {
      stockQuantity: 0,
      isEnabled: false,
      title: '',
      key: '',
      description: '',
      unit: '份',
      imageUrl: '',
      category: category,
      type: '',
      costPrice: 0,
      costCapacity: 100,
      content: undefined,
      nutrition: {
        calories: 0,
        proteinGrams: 0,
        carbsGrams: 0,
        fatGrams: 0,
      },
      price: 0,
      capacity: 0,
      allergenTag: [],
      VegetarianTag: '',
    },
    fixedPokes: {
      stockQuantity: 0,
      isEnabled: false,
      imageUrl: '',
      title: '',
      unit: '碗',
      description: '',
      category: category,
      type: '',
      price: 0,
      capacity: 0,
      contentSet: [{ name: '', capacity: 0 }],
      content: {
        base: [],
        protein: [],
        side: [],
        sauce: [],
        topping: [],
      },
      nutrition: {
        calories: 0,
        proteinGrams: 0,
        carbsGrams: 0,
        fatGrams: 0,
      },
      allergenTag: [],
      vegetarianTag: '',
    },
    otherProducts: {
      stockQuantity: 0,
      isEnabled: false,
      imageUrl: '',
      title: '',
      unit: '杯',
      description: '',
      category: category,
      type: '',
      price: 0,
      capacity: 0,
      contentSet: [{ name: '' }],
      content: [],
      nutrition: {
        calories: 0,
        proteinGrams: 0,
        carbsGrams: 0,
        fatGrams: 0,
      },
      allergenTag: [],
      VegetarianTag: '',
    },
  };
};
