export const FORMATTER_DATA = {
  type: {
    base: '基底',
    protein: '蛋白質',
    side: '配菜',
    sauce: '醬料',
    topping: '撒料',
    light: '輕食',
    balanced: '均衡',
    highProtein: '高蛋白',
    drink: '飲品',
    soup: '湯品',
  },
  nutrition: {
    calories: '熱量',
    proteinGrams: '蛋白量',
    carbsGrams: '碳水量',
    fatGrams: '脂肪量',
  },
  allergenTag: {
    beef: '牛肉',
    seafood: '海鮮',
    spicy: '辣',
    soy: '大豆',
    egg: '蛋',
    nuts: '堅果',
    sesame: '芝麻',
  },
  content: {
    rice: '白米',
    salmon: '鮭魚',
    tomato: '番茄',
    cucumber: '小黃瓜',
    papper: '青椒',
    spicyYolkSauce: '辣蛋黃醬',
    nuts: '碎堅果',
  },
};
